// This file centralizes the definition of all available tools, organized by category.
export const categories = [
  {
    name: 'Ferramentas Populares',
    tools: [
      {
        id: 'merge',
        name: 'Mesclar PDF',
        icon: 'combine',
        subtitle: 'Combinar múltiplos PDFs em um único arquivo.',
      },
      {
        id: 'split',
        name: 'Dividir PDF',
        icon: 'scissors',
        subtitle: 'Extrair um intervalo de páginas para um novo PDF.',
      },
      {
        id: 'compress',
        name: 'Comprimir PDF',
        icon: 'zap',
        subtitle: 'Reduzir o tamanho do arquivo do seu PDF.',
      },
      {
        id: 'edit',
        name: 'Editor de PDF',
        icon: 'pocket-knife',
        subtitle:
          'Anotar, destacar, redigir, comentar, adicionar formas/imagens, pesquisar e visualizar PDFs',
      },
      {
        id: 'jpg-to-pdf',
        name: 'JPG para PDF',
        icon: 'image-up',
        subtitle: 'Criar um PDF a partir de uma ou mais imagens JPG.',
      },
      {
        id: 'sign-pdf',
        name: 'Assinar PDF',
        icon: 'pen-tool',
        subtitle: 'Desenhar, digitar ou enviar sua assinatura.',
      },
      {
        id: 'cropper',
        name: 'Cortar PDF',
        icon: 'crop',
        subtitle: 'Aparar as margens de cada página do seu PDF.',
      },
      {
        id: 'extract-pages',
        name: 'Extrair Páginas',
        icon: 'ungroup',
        subtitle: 'Salvar uma seleção de páginas como novos arquivos.',
      },
      {
        id: 'duplicate-organize',
        name: 'Duplicar & Organizar',
        icon: 'files',
        subtitle: 'Duplicar, reordenar e excluir páginas.',
      },
      {
        id: 'delete-pages',
        name: 'Excluir Páginas',
        icon: 'trash-2',
        subtitle: 'Remover páginas específicas do seu documento.',
      },
    ],
  },
  {
    name: 'Edição & Anotação',
    tools: [
      {
        id: 'edit',
        name: 'Editor de PDF',
        icon: 'pocket-knife',
        subtitle:
          'Anotar, destacar, redigir, comentar, adicionar formas/imagens, pesquisar e visualizar PDFs.',
      },
      // { id: 'crop', name: 'Crop PDF', icon: 'crop', subtitle: 'Trim the margins of every page in your PDF.' },
      {
        id: 'add-page-numbers',
        name: 'Números de Página',
        icon: 'list-ordered',
        subtitle: 'Inserir números de página no seu documento.',
      },
      {
        id: 'add-watermark',
        name: 'Adicionar Marca d’Água',
        icon: 'droplets',
        subtitle: 'Estampar texto ou imagem sobre as páginas do seu PDF.',
      },
      {
        id: 'add-header-footer',
        name: 'Cabeçalho & Rodapé',
        icon: 'pilcrow',
        subtitle: 'Adicionar texto ao topo e ao rodapé das páginas.',
      },
      {
        id: 'invert-colors',
        name: 'Inverter Cores',
        icon: 'contrast',
        subtitle: 'Criar uma versão “modo escuro” do seu PDF.',
      },
      {
        id: 'change-background-color',
        name: 'Cor de Fundo',
        icon: 'palette',
        subtitle: 'Alterar a cor de fundo do seu PDF.',
      },
      {
        id: 'change-text-color',
        name: 'Alterar Cor do Texto',
        icon: 'type',
        subtitle: 'Alterar a cor do texto no seu PDF.',
      },
      {
        id: 'sign-pdf',
        name: 'Assinar PDF',
        icon: 'pen-tool',
        subtitle: 'Desenhar, digitar ou enviar sua assinatura.',
      },
      {
        id: 'remove-annotations',
        name: 'Remover Anotações',
        icon: 'eraser',
        subtitle: 'Remover comentários, destaques e links.',
      },
      {
        id: 'cropper',
        name: 'Cortar PDF',
        icon: 'crop',
        subtitle: 'Aparar as margens de cada página do seu PDF.',
      },
      {
        id: 'form-filler',
        name: 'Preencher Formulários PDF',
        icon: 'square-pen',
        subtitle: 'Preencher formulários diretamente no navegador.',
      },
      {
        id: 'remove-blank-pages',
        name: 'Remover Páginas em Branco',
        icon: 'file-minus-2',
        subtitle: 'Detectar e excluir páginas em branco automaticamente.',
      },
    ],
  },
  {
    name: 'Converter para PDF',
    tools: [
      {
        id: 'image-to-pdf',
        name: 'Imagem para PDF',
        icon: 'images',
        subtitle: 'Combinar várias imagens em um único PDF.',
      },
      {
        id: 'jpg-to-pdf',
        name: 'JPG para PDF',
        icon: 'image-up',
        subtitle: 'Criar um PDF a partir de uma ou mais imagens JPG.',
      },
      {
        id: 'png-to-pdf',
        name: 'PNG para PDF',
        icon: 'image-up',
        subtitle: 'Criar um PDF a partir de uma ou mais imagens PNG.',
      },
      {
        id: 'webp-to-pdf',
        name: 'WebP para PDF',
        icon: 'image-up',
        subtitle: 'Criar um PDF a partir de uma ou mais imagens WebP.',
      },
      {
        id: 'svg-to-pdf',
        name: 'SVG para PDF',
        icon: 'pen-tool',
        subtitle: 'Criar um PDF a partir de uma ou mais imagens SVG.',
      },
      {
        id: 'bmp-to-pdf',
        name: 'BMP para PDF',
        icon: 'image',
        subtitle: 'Criar um PDF a partir de uma ou mais imagens BMP.',
      },
      {
        id: 'heic-to-pdf',
        name: 'HEIC para PDF',
        icon: 'smartphone',
        subtitle: 'Criar um PDF a partir de uma ou mais imagens HEIC.',
      },
      {
        id: 'tiff-to-pdf',
        name: 'TIFF para PDF',
        icon: 'layers',
        subtitle: 'Criar um PDF a partir de uma ou mais imagens TIFF.',
      },
      {
        id: 'txt-to-pdf',
        name: 'Texto para PDF',
        icon: 'file-pen',
        subtitle: 'Converter um arquivo de texto simples em PDF.',
      },
      // { id: 'md-to-pdf', name: 'Markdown to PDF', icon: 'file-text', subtitle: 'Convert a Markdown file into a PDF.' },
      // { id: 'scan-to-pdf', name: 'Scan to PDF', icon: 'camera', subtitle: 'Use your camera to create a scanned PDF.' },
      // { id: 'word-to-pdf', name: 'Word to PDF', icon: 'file-text', subtitle: 'Convert .docx documents to PDF.' },
    ],
  },
  {
    name: 'Converter de PDF',
    tools: [
      {
        id: 'pdf-to-jpg',
        name: 'PDF para JPG',
        icon: 'file-image',
        subtitle: 'Converter cada página do PDF em uma imagem JPG.',
      },
      {
        id: 'pdf-to-png',
        name: 'PDF para PNG',
        icon: 'file-image',
        subtitle: 'Converter cada página do PDF em uma imagem PNG.',
      },
      {
        id: 'pdf-to-webp',
        name: 'PDF para WebP',
        icon: 'file-image',
        subtitle: 'Converter cada página do PDF em uma imagem WebP.',
      },
      {
        id: 'pdf-to-bmp',
        name: 'PDF para BMP',
        icon: 'file-image',
        subtitle: 'Converter cada página do PDF em uma imagem BMP.',
      },
      {
        id: 'pdf-to-tiff',
        name: 'PDF para TIFF',
        icon: 'file-image',
        subtitle: 'Converter cada página do PDF em uma imagem TIFF.',
      },
      {
        id: 'pdf-to-greyscale',
        name: 'PDF para Tons de Cinza',
        icon: 'palette',
        subtitle: 'Converter todas as cores para preto e branco.',
      },
      // { id: 'pdf-to-markdown', name: 'PDF to Markdown', icon: 'file-pen', subtitle: 'Extract text into a Markdown file.' },
    ],
  },
  {
    name: 'Organizar & Gerenciar',
    tools: [
      {
        id: 'ocr-pdf',
        name: 'OCR em PDF',
        icon: 'scan-text',
        subtitle: 'Tornar o PDF pesquisável e copiável.',
      },
      {
        id: 'merge',
        name: 'Mesclar PDF',
        icon: 'combine',
        subtitle: 'Combinar múltiplos PDFs em um único arquivo.',
      },
      {
        id: 'alternate-merge',
        name: 'Alternar & Misturar Páginas',
        icon: 'shuffle',
        subtitle: 'Combinar PDFs alternando páginas de cada um.',
      },
      {
        id: 'organize',
        name: 'Organizar PDF',
        icon: 'grip',
        subtitle: 'Reordenar páginas arrastando e soltando.',
      },
      {
        id: 'duplicate-organize',
        name: 'Duplicar & Organizar',
        icon: 'files',
        subtitle: 'Duplicar, reordenar e excluir páginas.',
      },
      {
        id: 'add-attachments',
        name: 'Adicionar Anexos',
        icon: 'paperclip',
        subtitle: 'Incorporar um ou mais arquivos ao seu PDF.',
      },
      {
        id: 'split',
        name: 'Dividir PDF',
        icon: 'scissors',
        subtitle: 'Extrair um intervalo de páginas para um novo PDF.',
      },
      {
        id: 'split-in-half',
        name: 'Dividir Páginas',
        icon: 'table-columns-split',
        subtitle: 'Dividir páginas horizontalmente ou verticalmente.',
      },
      {
        id: 'extract-pages',
        name: 'Extrair Páginas',
        icon: 'ungroup',
        subtitle: 'Salvar uma seleção de páginas como novos arquivos.',
      },
      {
        id: 'delete-pages',
        name: 'Excluir Páginas',
        icon: 'trash-2',
        subtitle: 'Remover páginas específicas do seu documento.',
      },
      {
        id: 'add-blank-page',
        name: 'Adicionar Página em Branco',
        icon: 'file-plus-2',
        subtitle: 'Inserir uma página vazia em qualquer lugar do seu PDF.',
      },
      {
        id: 'reverse-pages',
        name: 'Inverter Páginas',
        icon: 'arrow-down-z-a',
        subtitle: 'Inverter a ordem de todas as páginas do documento.',
      },
      {
        id: 'rotate',
        name: 'Rotacionar PDF',
        icon: 'rotate-cw',
        subtitle: 'Girar páginas em incrementos de 90 graus.',
      },
      {
        id: 'n-up',
        name: 'N-Up PDF',
        icon: 'layout-grid',
        subtitle: 'Dispor várias páginas em uma única folha.',
      },
      {
        id: 'combine-single-page',
        name: 'Combinar em Única Página',
        icon: 'unfold-vertical',
        subtitle: 'Unir todas as páginas em uma rolagem contínua.',
      },
      {
        id: 'view-metadata',
        name: 'Visualizar Metadados',
        icon: 'info',
        subtitle: 'Inspecionar propriedades ocultas do seu PDF.',
      },
      {
        id: 'edit-metadata',
        name: 'Editar Metadados',
        icon: 'file-cog',
        subtitle: 'Alterar autor, título e outras propriedades.',
      },
      {
        id: 'pdf-to-zip',
        name: 'PDFs para ZIP',
        icon: 'stretch-horizontal',
        subtitle: 'Empacotar múltiplos arquivos PDF em um arquivo ZIP.',
      },
      {
        id: 'compare-pdfs',
        name: 'Comparar PDFs',
        icon: 'git-compare',
        subtitle: 'Comparar dois PDFs lado a lado.',
      },
      {
        id: 'posterize',
        name: 'Posterizar PDF',
        icon: 'notepad-text-dashed',
        subtitle: 'Dividir uma página grande em múltiplas páginas menores.',
      },
    ],
  },
  {
    name: 'Otimizar & Reparar',
    tools: [
      {
        id: 'compress',
        name: 'Comprimir PDF',
        icon: 'zap',
        subtitle: 'Reduzir o tamanho do arquivo do seu PDF.',
      },
      {
        id: 'fix-dimensions',
        name: 'Corrigir Tamanho da Página',
        icon: 'ruler-dimension-line',
        subtitle: 'Padronizar todas as páginas para um tamanho uniforme.',
      },
      {
        id: 'linearize',
        name: 'Linearizar PDF',
        icon: 'gauge',
        subtitle: 'Otimizar PDF para visualização rápida na web.',
      },
      {
        id: 'page-dimensions',
        name: 'Dimensões da Página',
        icon: 'ruler',
        subtitle: 'Analisar tamanho, orientação e unidades da página.',
      },
      {
        id: 'remove-restrictions',
        name: 'Remover Restrições',
        icon: 'unlink',
        subtitle:
          'Remover proteção por senha e restrições de segurança associadas a PDFs assinados digitalmente.',
      },
    ],
  },
  {
    name: 'Proteger PDF',
    tools: [
      {
        id: 'encrypt',
        name: 'Criptografar PDF',
        icon: 'lock',
        subtitle: 'Proteger seu PDF adicionando uma senha.',
      },
      {
        id: 'sanitize-pdf',
        name: 'Sanitizar PDF',
        icon: 'brush-cleaning',
        subtitle: 'Remover metadados, anotações, scripts e mais.',
      },
      {
        id: 'decrypt',
        name: 'Descriptografar PDF',
        icon: 'unlock',
        subtitle: 'Desbloquear o PDF removendo a proteção por senha.',
      },
      {
        id: 'flatten',
        name: 'Achatar PDF',
        icon: 'layers',
        subtitle: 'Tornar campos de formulário e anotações não editáveis.',
      },
      {
        id: 'remove-metadata',
        name: 'Remover Metadados',
        icon: 'file-x',
        subtitle: 'Remover dados ocultos do seu PDF.',
      },
      {
        id: 'change-permissions',
        name: 'Alterar Permissões',
        icon: 'shield-check',
        subtitle: 'Definir ou alterar permissões de usuário em um PDF.',
      },
    ],
  },
];
